/* archlinux_boot_sequence */

(function () {
  const LINES = [
    { t: 'INFO', msg: 'Linux version 7.1.3-arch1-2 (helyz@archlinux) #1 SMP PREEMPT_DYNAMIC' },
    { t: 'INFO', msg: 'Command line: BOOT_IMAGE=/vmlinuz-linux root=UUID=6b66c6-a1b2 rw quiet' },
    { t: 'INFO', msg: 'x86/fpu: Supporting XSAVE feature 0x001: x87 floating point registers' },
    { t: 'INFO', msg: 'x86/fpu: Supporting XSAVE feature 0x002: SSE registers' },
    { t: 'INFO', msg: 'x86/fpu: xstate_offset[2]: 576, xstate_sizes[2]: 256' },
    { t: 'INFO', msg: 'BIOS-provided physical RAM map:' },
    { t: 'INFO', msg: 'BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] usable' },
    { t: 'INFO', msg: 'BIOS-e820: [mem 0x0000000100000000-0x000000047fffffff] usable' },
    { t: 'OK',   msg: 'NX (Execute Disable) protection: active' },
    { t: 'INFO', msg: 'SMBIOS 3.2.0 present.' },
    { t: 'INFO', msg: 'DMI: System76 Lemur Pro, BIOS 1.07.2 04/11/2024' },
    { t: 'INFO', msg: 'tsc: Fast TSC calibration using PIT' },
    { t: 'OK',   msg: 'tsc: Detected 2803.198 MHz processor' },
    { t: 'OK',   msg: 'e820: update [mem 0x00000000-0x00000fff] usable ==> reserved' },
    { t: 'INFO', msg: 'Zone ranges: DMA [mem 0x1000-0xffffff]' },
    { t: 'OK',   msg: 'ACPI: Early table checksum verification disabled' },
    { t: 'OK',   msg: 'ACPI: RSDP 0x00000000BFFCC014 000024 (v02 SYSTEM)' },
    { t: 'OK',   msg: 'ACPI: FACP 0x00000000BFF9E000 000114 (v06 SYSTEM)' },
    { t: 'INFO', msg: 'ACPI: Core revision 20230628' },
    { t: 'OK',   msg: 'PM: Registering ACPI NVS region [mem 0xbf000000-0xbf7fffff]' },
    { t: 'OK',   msg: 'PCI: Using ACPI for IRQ routing' },
    { t: 'INFO', msg: 'pci 0000:00:02.0: vgaarb: setting as boot VGA device' },
    { t: 'OK',   msg: 'clocksource: refined-jiffies: mask 0xffffffff' },
    { t: 'OK',   msg: 'clocksource: Switched to clocksource tsc-early' },
    { t: 'OK',   msg: "Loaded X.509 cert 'Build time autogenerated kernel key'" },
    { t: 'OK',   msg: 'zbud: loaded' },
    { t: 'OK',   msg: 'Key type asymmetric registered' },
    { t: 'OK',   msg: 'Block layer SCSI generic (bsg) driver version 0.4' },
    { t: 'OK',   msg: 'io scheduler mq-deadline registered' },
    { t: 'OK',   msg: 'io scheduler kyber registered' },
    { t: 'OK',   msg: 'io scheduler bfq registered' },
    { t: 'INFO', msg: 'nvme nvme0: pci function 0000:01:00.0' },
    { t: 'OK',   msg: 'nvme nvme0: 8/0/0 default/read/poll queues' },
    { t: 'OK',   msg: 'nvme0n1: p1 p2 p3' },
    { t: 'OK',   msg: 'usb 1-3: new high-speed USB device number 4' },
    { t: 'OK',   msg: 'usbcore: registered new interface driver usbfs' },
    { t: 'OK',   msg: 'usbcore: registered new interface driver hub' },
    { t: 'OK',   msg: 'i8042: PNP: PS/2 Controller detected' },
    { t: 'OK',   msg: 'serio: i8042 KBD port at 0x60 irq 1' },
    { t: 'OK',   msg: 'rtc_cmos 00:00: registered as rtc0' },
    { t: 'OK',   msg: 'thermal_sys: registered cooling device 0' },
    { t: 'OK',   msg: 'cfg80211: Loading compiled-in X.509 certificates' },
    { t: 'OK',   msg: 'iwlwifi 0000:00:14.3: loaded firmware version 89.7f5eb844.0' },
    { t: 'OK',   msg: 'Bluetooth: hci0: Bootloader revision 0.1' },
    { t: 'OK',   msg: 'ALSA sound/soc/sof: firmware boot complete' },
    { t: 'OK',   msg: 'snd_hda_intel 0000:00:1f.3: bound (registered)' },
    { t: 'OK',   msg: 'Adding 8388604k swap on /dev/nvme0n1p3.' },
    { t: 'OK',   msg: 'EXT4-fs (nvme0n1p2): mounted filesystem with ordered data mode' },
    { t: 'OK',   msg: 'VFS: Mounted root (ext4 filesystem) readonly on device 259:2' },
    { t: 'OK',   msg: 'devtmpfs: mounted' },
    { t: 'OK',   msg: 'Freeing unused kernel image memory' },
    { t: 'OK',   msg: 'Write protecting kernel text and read-only data' },
    { t: 'OK',   msg: 'x86/mm: Checked W+X mappings: passed, no W+X pages found' },
    { t: 'OK',   msg: 'systemd[1]: Detected architecture x86-64.' },
    { t: 'OK',   msg: 'systemd[1]: Hostname set to <archlinux>.' },
    { t: 'OK',   msg: 'Started Journal Service.' },
    { t: 'OK',   msg: 'Mounted /boot/efi.' },
    { t: 'OK',   msg: 'Mounted /home.' },
    { t: 'OK',   msg: 'Reached target Local File Systems.' },
    { t: 'OK',   msg: 'Started Create Volatile Files and Directories.' },
    { t: 'INFO', msg: 'If you read this, DM me "Aila Jyrkiäinen" on Discord :3'},
    { t: 'OK',   msg: 'Started Create System Users.' },
    { t: 'OK',   msg: 'Started udev Coldplug all Devices.' },
    { t: 'OK',   msg: 'Found device /dev/nvme0n1p2.' },
    { t: 'OK',   msg: 'Started Load/Save Random Seed.' },
    { t: 'OK',   msg: 'Started Apply Kernel Variables.' },
    { t: 'OK',   msg: 'Reached target System Initialization.' },
    { t: 'OK',   msg: 'Started Daily Cleanup of Temporary Directories.' },
    { t: 'OK',   msg: 'Reached target Timers.' },
    { t: 'OK',   msg: 'Listening on D-Bus System Message Bus Socket.' },
    { t: 'OK',   msg: 'Reached target Sockets.' },
    { t: 'OK',   msg: 'Reached target Basic System.' },
    { t: 'OK',   msg: 'Started dbus-broker.service.' },
    { t: 'OK',   msg: 'Started Load Kernel Module drm.' },
    { t: 'OK',   msg: 'Started NetworkManager.' },
    { t: '....', msg: 'Starting Network Manager Wait Online...' },
    { t: 'OK',   msg: 'Reached target Network.' },
    { t: 'OK',   msg: 'Started OpenSSH Daemon.' },
    { t: 'OK',   msg: 'Reached target Network is Online.' },
    { t: 'OK',   msg: 'Started Bluetooth service.' },
    { t: 'OK',   msg: 'Started ModemManager.' },
    { t: 'OK',   msg: 'Started Accounts Service.' },
    { t: 'OK',   msg: 'Started Time & Date Service.' },
    { t: 'OK',   msg: 'Started Disk Manager.' },
    { t: 'OK',   msg: 'Started Rule-based Manager for Device Events and Files.' },
    { t: 'OK',   msg: 'Started CUPS Scheduler.' },
    { t: 'OK',   msg: 'Started Login Service.' },
    { t: 'OK',   msg: 'Started ufw firewall.' },
    { t: 'INFO', msg: 'ufw: default deny incoming, allow outgoing' },
    { t: 'OK',   msg: 'Reached target Multi-User System.' },
    { t: 'OK',   msg: 'Started Getty on tty1.' },
    { t: 'INFO', msg: 'archlinux login: helyz' },
    { t: 'OK',   msg: 'pam_unix(login:session): session opened for user helyz' },
    { t: 'OK',   msg: 'Started Session c1 of user helyz.' },
    { t: 'INFO', msg: 'Starting Hyprland compositor...' },
    { t: 'OK',   msg: 'Reached target Graphical Interface.' },
    { t: 'OK',   msg: 'Started XDG Desktop Portal.' },
    { t: 'INFO', msg: 'waybar: config loaded, 14 modules active' },
    { t: 'OK',   msg: 'Started polkit-agent.' },
    { t: 'OK',   msg: 'Started GPG password agent.' },
    { t: 'OK',   msg: 'Started keepassxc.' },
    { t: 'OK',   msg: 'Started Docker Application Container Engine.' },
    { t: 'OK',   msg: 'Started containerd.service.' },
    { t: 'OK',   msg: 'Started PostgreSQL database server.' },
    { t: 'OK',   msg: 'Started Redis Persistent Key-Value Database.' },
    { t: 'OK',   msg: 'Started The nginx HTTP and reverse proxy server.' },
    { t: 'OK',   msg: 'Started WireGuard Tunnel wg0.' },
    { t: 'INFO', msg: 'wg0: peer handshake completed' },
    { t: 'OK',   msg: 'nvidia-smi: driver version 550.78 loaded' },
    { t: 'INFO', msg: 'Lyze{f0r_7h3_gl0ry_0f_m@nk1nd}'},
    { t: 'OK',   msg: 'Started tmux server.' },
    { t: 'OK',   msg: 'Started NTP time synchronization.' },
    { t: 'WARN', msg: 'clock skew detected, ntpd resyncing...' },
    { t: 'OK',   msg: 'ntpd: synced to pool.ntp.org (offset 0.003s)' },
    { t: 'WARN', msg: 'thermal: CPU package temp 71C, fan curve adjusted' },
    { t: 'OK',   msg: 'thermald: throttling not required' },
    { t: 'OK',   msg: 'Mounted /mnt/writeups.' },
    { t: 'OK',   msg: 'Reached target Default.' },
    { t: 'INFO', msg: 'systemd[1]: Startup finished in 1.482s (kernel) + 2.107s (initrd) + 3.981s (userspace) = 7.570s.' },
    { t: 'INFO', msg: 'fortune: carpe noctem.' },
    { t: 'INFO', msg: 'motd: "truth lies in the eyes of the beholder"' },
    { t: 'INFO', msg: 'session uptime: 1337 minutes' },
    { t: 'OK',   msg: 'Reached target Multi-User System.' },
  ];
  const MAX_VISIBLE = 67;
  const LINE_DELAY  = 7;
  const LOOP_PAUSE  = 6769;

  function injectCSS() {
    const css = `
      #boot-seq {
        position: fixed; left: 0; top: 0; bottom: 0;
        width: 50vw; max-width: 640px; padding: 1.4rem 1rem;
        font-family: 'JetBrains Mono', 'Fira Code', monospace;
        font-size: .70rem; line-height: 1.65;
        color: #6b66c6; opacity: .55;
        background: linear-gradient(90deg, rgba(10,10,8,.4), transparent);
        pointer-events: none; user-select: none;
        overflow: hidden; z-index: 40;
        display: flex; flex-direction: column; justify-content: flex-end;
      }
      #boot-seq .bl { white-space: nowrap; }
      #boot-seq .bl .tag { color: #6b66c6; font-weight: 700; }
      #boot-seq .bl .tag.info { color: #9a96e0; }
      #boot-seq .bl .tag.warn { color: #e0a86b; }
      #boot-seq .bl .msg { color: #9a96e0; opacity: .8; }
      #boot-seq .cursor { display:inline-block; width:6px; height:10px; background:#6b66c6; animation: bseq-blink 1s step-end infinite; }
      @keyframes bseq-blink { 50% { opacity: 0; } }
      @media (max-width: 1500px) { #boot-seq { display: none; } }
    `;
    const tag = document.createElement('style');
    tag.textContent = css;
    document.head.appendChild(tag);
  }

  function injectHTML() {
    const wrap = document.createElement('div');
    wrap.id = 'boot-seq';
    document.body.appendChild(wrap);
    return wrap;
  }

  function fmtTag(t) {
    if (t === 'OK')   return `<span class="tag">[  OK  ]</span>`;
    if (t === '....') return `<span class="tag">[ .... ]</span>`;
    if (t === 'WARN') return `<span class="tag warn">[ WARN ]</span>`;
    return `<span class="tag info">[ INFO ]</span>`;
  }

  function run(el) {
    el.innerHTML = '';
    let i = 0;
    const rendered = [];

    function tick() {
      if (i >= LINES.length) {
        setTimeout(() => run(el), LOOP_PAUSE);
        return;
      }
      const { t, msg } = LINES[i++];
      rendered.push(`<div class="bl">${fmtTag(t)} <span class="msg">${msg}</span></div>`);
      while (rendered.length > MAX_VISIBLE) rendered.shift();
      el.innerHTML = rendered.join('') + `<div class="bl"><span class="cursor"></span></div>`;
      setTimeout(tick, LINE_DELAY + Math.random() * 180);
    }
    tick();
  }

  function init() {
    injectCSS();
    const el = injectHTML();
    run(el);
  }

  document.readyState === 'loading'
    ? document.addEventListener('DOMContentLoaded', init)
    : init();
})();
